# Generated by Django 4.0.4 on 2022-05-20 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aimark', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mark',
            name='image',
            field=models.ImageField(upload_to=''),
        ),
    ]
