# Generated by Django 4.0.4 on 2022-05-20 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aimark', '0002_alter_mark_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mark',
            name='user',
        ),
    ]
