# Generated by Django 4.0.4 on 2022-05-20 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aimark', '0003_remove_mark_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mark',
            name='image',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
